- changelog.md
- example/App.tsx
- package.json
- src/api/data.ts
- src/api/index.ts
- src/apis.json
- src/types/index.ts
Add data API.  Note that this API wrapper is gated with a flag and won't work until we release to everyone.
```js
import { data } from '@replit/extensions';
await data.user.current();
await data.repl.byId({
id: "asdf-asdf-asdf-asdf-asdf"
})
await data.user.byUsername({
username: "amasad",
includeSocialData: true,
includeRoles: true
});
```
> Add Data API to extensions repo

- src/react/useReplitEffect.ts
The react warning about useLayoutEffect is really getting on my nerves.  Switching to plain `useEffect` supresses this in React when using an SSR framework like Next.js.
> [useReplitEffect] Switch to useEffect rather than useLayoutEffect

- src/api/fs/watching.ts
We serialize the changset using `toJSON` in the workspace, I assumed we serialized it to a `ChangeSpec` compliant format.  I'm not sure how I didn't catch this issue earlier in my testing, but it works now.
Use `ChangeSet.fromJSON` instead of `ChangeSet.of` to create the changeset
You can test it in my repl here https://replit.com/@replitfaris/extensions#dev/test.ts
> Fix file watching not working

- README.md
The invite link for the Replit Devs Discord server in the README was wrong.
> Fix Discord invite link in README

- package.json
Creating a nodejs repl and importing stuff from `@replit/extensions` or `@replit/extensions/react` doesn't work since everything but nodejs module resolution works.
> Add support for nodejs module resolution

- src/react/useIsExtension.ts
Sometimes users might want to render UI conditionally, or have an application that works as both an extension and a non-extension.
> useIsExtension hook

- example/App.tsx
- src/apis.json
- src/index.ts
- src/react/useReplit.ts
- src/types/index.ts
In a non-react Repl, it is very hard to see whether the handshake between Replit and the extension was established successfully.  Added an `onHandshakeStatus` callback in the init function and also removed an unused function.  Updated the useReplit hook to work with this as well.
> Improve init() function

- src/index.ts
Right now, when you call replit.init() before the document completes loading, it hangs forever. This happens because the replit workspace side extension port only starts listening for messages when loading completes. 
We currently solve for this in some of our templates by waiting for the document to complete loading, but we can wait for that ourselves and save extension authors the trouble.
> Wait for window to load before attempting handshake

- modules/extensions-react/src/hooks/useReplitEffect.ts
Typescript is not happy when you don't provide a dependency array in the useReplitEffect hook (second param).  Bad for devex.
> [React Client] Optional dependency array in useReplitEffect

- modules/example/package.json
- modules/extensions/package.json
- modules/extensions/src/api/index.ts
- modules/extensions/src/api/internal/auth.ts
- modules/extensions/src/api/internal/index.ts
- modules/extensions/src/types/index.ts
- pnpm-lock.yaml
This adds an Auth API to the extensions client, making it possible for an extension frontend or backend to reliably know if an extension has been loaded by replit
> Add Auth API

- modules/example/App.tsx
- modules/extensions/src/api/data.ts
- modules/extensions/src/api/experimental/editor.ts
- modules/extensions/src/api/experimental/index.ts
- modules/extensions/src/apis.json
- modules/extensions/src/types/data.ts
- modules/extensions/src/types/index.ts
Some users have been requesting to user editor preferences through the data module.  This PR allows accessing it through the `currentUser` query.
Waiting on https://github.com/replit/repl-it-web/pull/32098 to reach prod first.
> Add User Editor Preferences to the Data Module

- modules/extensions/src/index.ts
Useful for debugging reasons
This lets you access the version of this package by running `replit.version` or `import { version } from '@replit/extensions'`
> Exported version from package

- modules/extensions/package.json
We imported `jose` in #60 which worked fine in our example (which loaded ES modules) but broke our unpkg imports since we were accidentally bundling for node and not the browser
I tested this by:
- `pnpm build`
- copy `modules/extensions/dist/index.global.js`
- paste into browser
- no error!
You can reproduce the current error by following those steps off the main branch before this is PR merged
The `--platform` option I made use of is actually undocumented in tsup docs
> Fix platform

- .github/workflows/ci.yaml
- modules/extensions/buildTests/build.test.tsx
- modules/extensions/jest-setup.js
- modules/extensions/jest.config.js
- modules/extensions/package.json
- package.json
- pnpm-lock.yaml
- turbo.json
We accidentally broke the IIFE build because our example app doesn't make use of it.
To prevent that (and other build related incidents) from happening again, I added some tests to make sure our build looks like what we expect it to look like, and that the IIFE code, when invoked, successfully produces `replit` instead of throwing an error. This is just a start, obviously.
These are in form of jest w/ JSDOM tests that run on the completed build. You can trigger them by running `pnpm test:build` at the root, which is dependent on the build command having been run on the source code first
Finally, I added a GH action to make sure we're always in good shape and catch any issues as they happen
> Add build tests

- modules/extensions/buildTests/build.test.tsx
- modules/extensions/package.json
- package.json
- pnpm-lock.yaml
- tsconfig.json
If you didn't have jest installed globally, Typescript said that `describe` and `expect` were not defined.  Installed jest in the global package.json and fixed up a few things.
> Make Tests + TS happy

- modules/extensions/src/api/data.ts
- modules/extensions/src/api/replDb.ts
It's annoying to have to do `data.currentUser({})` with an empty object since no additional fields are getting fetched.  Added the option to not provide the argument at all to a few methods.
> Add optional parameters for devex

- modules/extensions/src/api/experimental/exec.ts
- modules/extensions/src/api/experimental/index.ts
- modules/extensions/src/types/exec.ts
the exec API has a somewhat verbose syntax. To just run a command, you need to do:
```javascript
const { promise, dispose } = await replit.exec({ args: "npm i" });
const {output, error, exitCode} = await promise;
if (error) {
throw error;
}
if (exitCode !== 0) {
throw new Error("Non zero exit code")
}
```
While we intended to have a simpler API, some complexity crept in because we wanted to support some use cases like long running processes (with the ability to kill them), and have the ability to consume stdout and stderr separately.
But I just don't wanna write all that code to run a simple command in the container. Most people will probably end up wrapping that method for simplicity. We should just do it ourselves.
Now I can just call 
```javascript
const { stdout, stderr } = await …
```
> [exec] executeCommand & exec APIs

- modules/extensions/package.json
- modules/extensions/src/api/experimental/auth.ts
- modules/extensions/src/index.ts
- modules/extensions/src/polyfills/ed25519.ts
- package.json
- patches/jose@4.14.4.patch
- pnpm-lock.yaml
- We switched to ed25519 but the browser support for that is pretty limited, so we're using a library to polyfill SubtleCrypto behavior for `jose`.
- `jose` itself needed a patch to accept these keys made by our polyfill
- the auth endpoint now returns a result type instead of just the result
> Auth API changes

- modules/dev/src/components/Header.tsx
- modules/dev/src/components/Test.tsx
- modules/dev/src/tests/actionRequired.ts
- modules/dev/src/tests/index.ts
- modules/dev/src/tests/session.ts
- modules/dev/src/tests/themes.ts
- modules/dev/src/types.ts
Added two buttons, one of which runs required tests and the other that runs all tests.  Action-required tests require you to perform an action (e.g. switching a theme or going to different files).
> Separate Action-Required Tests from Required tests

- modules/dev/src/tests/themes.ts
The tests don't work if you are on the two inbuilt themes, because their ids are strings and not numbers. I adapted the tests to work for both inbuilt and custom themes.
> Fixed theme test

- modules/extensions/src/index.ts
- modules/extensions/src/util/patchConsole.ts
If you call replit.init() multiple times, we patch the console multiple times, which is annoying
> Fixed duplicate console patching

- modules/extensions/changelog.md
- modules/extensions/package.json
- modules/extensions/src/api/experimental/commands.ts
- modules/extensions/src/commands/index.ts
- modules/extensions/src/types/index.ts
Describing a command is very verbose at the moment. 
- This simplifies it by removing the need to nest everything under `data`. Instead we add validation to make sure everything apart from `commands` and `run` is serializable. 
- I also improved the typing, so validation is done by the type system before code is even run (but there's still runtime validation in case people use this in a non javascript context or typechecking is disabled / fails)
- I added type docs
Here's an example invocation:
```typescript
await replit.experimental.commands.register(Command({
id: 'example',
label: 'Example command',
contributions: ['commandbar'],
commands: async () => {
return [
Command({
label: 'nice',
run: () => {}
}),
]
}
}))
```
> [extensions] simplified command API invocation

- modules/extensions/src/api/experimental/commands.ts
- modules/extensions/src/commands/index.ts
- modules/extensions/src/types/index.ts
`register` and `registerCreate` sound... bureaucratic. We also want a single syntax for creating commands directly or via passing a function that creates a command. 
This is a wrapper on top of the registerCreateCommand API that does just that!
- Added `add`. When you call `commands.add`, you first provide it with an id and a contribution point array, and it returns a curried function. That function can be called, either with a command, or a function that creates a command
> [extensions] added the nicer commands.add call

- modules/extensions/src/api/experimental/commands.ts
- modules/extensions/src/apis.json
- modules/extensions/src/commands/index.ts
I'm not totally sure I'm doing this right, the docs setup is super confusing lol.
> Add command api to docs json

- modules/extensions/src/api/experimental/commands.ts
- modules/extensions/src/commands/index.ts
The 'contributions' array is typed to take in any string, when in reality only 4 strings are currently accepted (and all others are no-ops)
- Added ContributionType enum, made use of it everywhere
> [commands] add contribution types

- modules/extensions/src/api/experimental/commands.ts
- modules/extensions/src/commands/index.ts
- modules/extensions/src/types/index.ts
Currently, we make you wrap every single command, even nested ones. The invocation looks like
```javascript
await replit.experimental.commands.add(
{ id: "hey", contributions: ["commandbar"] },
Command({
label: "hey",
description: "hey commands",
commands: () => {
return [
Command({
label: "hello",
description: "says hello",
run: () => console.log("hello"),
}),
Command({
label: "hola",
description: "says hola",
run: () => console.log("hola"),
}),
];
},
}),
);
```
It would be nice to not have to wrap things in Command(). The client library can simply do it for you.
```javascript
await replit.experimental.commands.add(
{ id: "hey", contributions: ["commandbar"] },
{
label: "hey",
description: "hey commands",
commands: () => {
return [
{
label: "hello",
description: "says hello",
run: () => …
```
> [commands] provide command args directly
